name: Build&Publish

permissions:
  contents: write

on:
  push:
    branches: [ "main", "master", "ci-test" ]
    tags: [ "v*" ]

env:
  APP_NAME: mcp_server

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          requirements: 'requirements.txt'
          upload_exe_with_name: ${{ env.APP_NAME }}
          options: --onefile, --name ${{ env.APP_NAME }}, --windowed