name: Build&Publish

permissions:
  contents: write

on:
  push:
    branches: [ "main", "master", "ci-test" ]
    tags: [ "v*" ]

env:
  APP_NAME: mcp_server
  PYTHON_VERSION: 3.12

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller mcp_server.py --onefile --name ${{ env.APP_NAME }}

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}
          path: dist/${{ env.APP_NAME }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for ${{ env.APP_NAME }}"
          files: |
            dist/${{ env.APP_NAME }}